### ISSUE TITLE
[BUG] avx512, aggregated logical set is broken

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#510]
The following test case:

```
TTS_CASE_TPL("logical getters and setters double size", EVE_TYPE)
{
  eve::logical<eve::wide<EVE_VALUE, eve::fixed<EVE_CARDINAL * 2>>> x{false};

  for (int i = 0; i != T::static_size; ++i) {
    TTS_EXPECT_NOT(x.get(i));
    x.set(i, true);
    TTS_EXPECT(x.get(i));
    x.set(i, false);
    TTS_EXPECT_NOT(x.get(i));
  }
}
```

Fails with asan:

```
=================================================================
==197568==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff4504a3a2 at pc 0x0000004a9737 bp 0x7fff4504a250 sp 0x7fff45049a18
READ of size 8 at 0x7fff4504a3a2 thread T0
    #0 0x4a9736 in __asan_memcpy /home/dyarosh/space/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
    #1 0x54bf5a in void tts_function3<eve::wide<double, eve::fixed<8l>, eve::x86_512_> >(tts::detail::env&, bool, tts::options const&) (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x54bf5a)
    #2 0x54b77f in auto (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()<tts::detail::box<eve::wide<double, tts::detail::box::fixed<8l>, tts::detail::box::x86_512_> > >((anonymous namespace)::register_tts_function3) const::'lambda'(tts::env&, bool, (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()::options const&)::operator()(tts::env, bool, (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()::options const) const (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x54b77f)
    #3 0x54b73c in auto (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()<tts::detail::box<eve::wide<double, tts::detail::box::fixed<8l>, tts::detail::box::x86_512_> > >((anonymous namespace)::register_tts_function3) const::'lambda'(tts::env&, bool, (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()::options const&)::__invoke(tts::env, bool, (anonymous namespace)::register_tts_function3::'lambda'(auto)::operator()::options const) (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x54b73c)
    #4 0x56ecfa in tts::detail::test::operator()(tts::detail::env&, bool, tts::options const&) (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x56ecfa)
    #5 0x4de660 in eve_entry_point(int, char const**) (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x4de660)
    #6 0x4dea01 in main (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x4dea01)
    #7 0x7fd9ebc9c0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x42f29d in _start (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x42f29d)

Address 0x7fff4504a3a2 is located in stack of thread T0 at offset 322 in frame
    #0 0x54b79f in void tts_function3<eve::wide<double, eve::fixed<8l>, eve::x86_512_> >(tts::detail::env&, bool, tts::options const&) (/home/dyarosh/space/eve/build_avx512/unit/unit.api.logical.regular.simd.exe+0x54b79f)

  This frame has 31 object(s):
    [32, 40) 'retval.i.i355'
    [64, 72) 'retval.i359'
    [96, 104) 'retval.i.i310'
    [128, 136) 'retval.i314'
    [160, 168) 'retval.i.i'
    [192, 200) 'retval.i'
    [224, 225) 'retval.i.i.i.i.i'
    [240, 241) 'ref.tmp.i.i.i.i'
    [256, 257) 'ref.tmp2.i.i.i.i'
    [272, 273) 'agg.tmp.i.i.i'
    [288, 290) 'ref.tmp.i'
    [304, 305) 'ref.tmp2.i'
    [320, 322) 'x' <== Memory access at offset 322 overflows this variable
    [336, 440) 'tts_var_d'
    [480, 488) 'ref.tmp'
    [512, 513) 'ref.tmp1'
    [528, 536) 'ref.tmp2'
    [560, 576) 'ref.tmp6'
    [592, 608) 'ref.tmp49'
    [624, 728) 'tts_var_d83'
    [768, 776) 'ref.tmp84'
    [800, 801) 'ref.tmp85'
    [816, 824) 'ref.tmp86'
    [848, 864) 'ref.tmp95'
    [880, 896) 'ref.tmp126'
    [912, 1016) 'tts_var_d185'
    [1056, 1064) 'ref.tmp186'
    [1088, 1089) 'ref.tmp187'
    [1104, 1112) 'ref.tmp188'
    [1136, 1152) 'ref.tmp195'
    [1168, 1184) 'ref.tmp250'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/dyarosh/space/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x100068a01420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100068a01430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100068a01440: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x100068a01450: f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
  0x100068a01460: 00 f2 f2 f2 00 f2 f2 f2 f8 f2 f8 f2 f8 f2 f8 f2
=>0x100068a01470: f8 f2 f8 f2[02]f2 00 00 00 00 00 00 00 00 00 00
  0x100068a01480: 00 00 00 f2 f2 f2 f2 f2 00 f2 f2 f2 01 f2 00 f2
  0x100068a01490: f2 f2 f8 f8 f2 f2 f8 f8 f2 f2 f8 f8 f8 f8 f8 f8
  0x100068a014a0: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f8 f2 f2 f2
  0x100068a014b0: f8 f2 f8 f2 f2 f2 f8 f8 f2 f2 f8 f8 f2 f2 f8 f8
  0x100068a014c0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==197568==ABORTING
```

**Comment by jfalcou** [comment]
This maybe requires we wrote set and get explicitly as loading/storing to regular memory THEN extracting/setting the value properly. 

On the other side, aggregated AVX512 means we have 1024+ bits "register" and I am not sure this make sense w/r to the architecture layout of the cache.

**Comment by jfalcou** [comment]
Superseded by #974
